[project]
name = "sistema-solar"
version = "0.1.0"
description = "Aplicativo simples feito em python sobre o sistema solar"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
]
